name: SkyWars
authors: [svile, Laith98Dev]
description: SkyWars plugin
main: svile\skywars\SWmain
version: 1.8.0
api: [4.0.0]
load: STARTUP
depend: [EconomyAPI]

commands:
 sw:
  description: SkyWars main command
  permission: sw.command

permissions:
  sw.command:
    default: op
  sw.command.join:
    default: true
  sw.command.quit:
    default: true
  sw.setsign:
    default: op
  sw.removesign:
    default: op
  
